languages:
    JavaScript: true
    Python: true

exclude_paths:
- "test/*"

engines:
  rubocop:
    enabled: true
  golint:
    enabled: true
  gofmt:
    enabled: true
  csslint:
    enabled: true

ratings:
   paths:
   - app/**
   - lib/**
   - "**.css"
   - "**.rb"
   - "**.go"

exclude_paths:
- "**/lib/**"
- "**/vendor/**"
- spec/**/*
- vendor/**/*
