sudo: required
language: java
jdk: oraclejdk8
services:
- docker
cache:
  directories:
  - $HOME/.m2
  - $HOME/maven
env:
  matrix:
  - MAVEN_VERSION=3.3.9 TEST=core
  - MAVEN_VERSION=3.3.9 TEST=python-validator
  - MAVEN_VERSION=3.3.9 TEST=end-to-end
  - MAVEN_VERSION=3.3.9 TEST=end-to-end-webdriverio
  global:
  - secure: fLGTh5E5YSSBKZEexj4tpvhyNlR98NNEUBrhkO9nVzn8W4XDkui1wjT6VSqhTauOWc9dMHou7fXgn2bxnXKYuMozijIoK8dtEJpE2mJ+HEb42Wjn776ou0kqg/JBFguY+Q+GWAUhtjjzeMlKawDBxsB15+DfKtZ2o8ZOU9ibzaw=
  - secure: okcDVSIqgIdLKww9FRa64r8ieJ5zmreXsrDLrDso9Kh7j6BA6bcNllv+QrjjHIMQTvauXwFc8eCI3bpWQgPQB0yQbg+UPnm8MihA42B1cqCBNumSnmyOzKcHOAP/nFCKLUrfH188magpmf22iq3NJgmlvt6uJKQrCRTNHrECfEY=
before_install:
- |
  if [[ "${TEST}" == end-to-end-webdriverio ]]
    then
        if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi &&
        nvm install 6 && \
        node --version && \
        npm install -g webdriverio wdio-spec-reporter wdio-mocha-framework wdio-browserstack-service
    fi
install:
- |
  if [[ "${TEST}" == core || "${TEST}" =~ ^end-to-end.* ]]
  then
      mkdir -p ~/maven
      test -d ~/maven/$MAVEN_VERSION/bin || { \
          find ~/maven -mindepth 1 -delete && \
          mkdir -p ~/maven/$MAVEN_VERSION && \
          wget -O - http://www-us.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz | \
              tar -C ~/maven/$MAVEN_VERSION --strip-components=1 -xzf -; }
  fi
- |
  if [[ "${TEST}" == python-validator ]]
  then
      sudo -H pip install -r requirements.txt
  fi
before_script:
- |
  if [[ "${TEST}" == core ]]
  then
      mysql --user root --password= <<< 'CREATE DATABASE cgds_test' && \
      mysql --user root --password= <<< "CREATE USER 'cbio_user'@'localhost' IDENTIFIED BY 'somepassword'" && \
      mysql --user root --password= <<< "GRANT ALL ON cgds_test.* TO 'cbio_user'@'localhost'" && \
      mysql --user root --password= <<< "flush privileges"
  fi
script:
- export PORTAL_HOME=$(pwd)
- |
  if [[ "${TEST}" == python-validator ]]
  then
      export PYTHONPATH=$PYTHONPATH:$PORTAL_HOME/core/src/main/scripts:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages && \
      cd $PORTAL_HOME/core/src/test/scripts/ && \
      $PORTAL_HOME/core/src/test/scripts/./unit_tests_validate_data.py && \
      $PORTAL_HOME/core/src/test/scripts/./system_tests_validate_data.py && \
      cd $PORTAL_HOME
  fi
- |
  if [[ "${TEST}" == core ]]
  then
      mkdir -p ~/.m2 && \
      cp .travis/settings.xml ~/.m2
  fi
- |
  if [[ "${TEST}" == core ]]
  then
      ~/maven/$MAVEN_VERSION/bin/mvn \
          -e \
          -DPORTAL_HOME=$PORTAL_HOME \
          -Ppublic \
          -Dfinal.war.name=cbioportal \
          -Ddb.user=cbio_user \
          -Ddb.password=somepassword \
          -Ddb.host=127.0.0.1 \
          -Ddb.connection_string=jdbc:mysql://127.0.0.1:3306/ \
          clean integration-test
  fi
- |
  if [[ "${TEST}" =~ ^end-to-end.* ]]
  then
      ~/maven/$MAVEN_VERSION/bin/mvn \
          -e -DPORTAL_HOME=$PORTAL_HOME \
          -Ppublic -DskipTests \
          -Dfinal.war.name=cbioportal \
          -Ddb.user=cbio_user \
          -Ddb.password=cbio_pass \
          -Ddb.portal_db_name=public_test \
          -Ddb.connection_string=jdbc:mysql://sm4sa6ozhn5ya6.cuooweljyhix.us-east-1.rds.amazonaws.com:3306/ \
          -Ddb.host=sm4sa6ozhn5ya6.cuooweljyhix.us-east-1.rds.amazonaws.com \
          clean install
  fi
- |
  if [[ "${TEST}" == end-to-end ]]
  then
      cd test/end-to-end && \
      docker-compose up -d && \
      sleep 30s && \
      cd ../.. && \
      # spot visual regression by comparing screenshots in the repo with
      # screenshots of this portal loaded with the data from the amazon db
      bash test/end-to-end/test_make_screenshots.sh test/end-to-end/screenshots.yml
  fi
- |
  if [[ "${TEST}" == end-to-end-webdriverio ]]
  then
      cd test/end-to-end && \
      docker-compose up -d cbioportal && \
      cd ../.. && \
      sleep 20s && \
      wdio wdio.conf.js
  fi
notifications:
  slack: cbioportal:S2qVTFTFMtizONhCOe8BYxS6
